spring:
  datasource:
    username: username
    password: password
    url: url
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

  security:
    enabled: false

  health:
    defaults:
      enabled: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

gameservice:
  version: ${project.version}
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-1
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true