spring:
  datasource:
    url: jdbc:mysql://java-gameservices.covj7lnh9ex6.us-west-1.rds.amazonaws.com:3306/sys
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

  cloud:
    gateway:
      routes:
        - id: inventoryService
          uri: http://localhost:9000
          predicates:
            - Path="/inventory/**"
        - id: characterService
          uri: http://localhost:9001
          predicates:
            - Path=/character/**

  security:
    enabled: false

  health:
    defaults:
      enabled: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-1
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
server:
  port: 8999
