spring:
  security:
    user:
      name: sa
      password: password
  datasource:
    url: jdbc:h2:file:~/data/inventory
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

gameservice:
  services:
    - name: inventory
      host: localhost
      uri: /inventory
      port: 9000
    - name: characters
      host: localhost
      uri: /characters
      port: 9001
    - name: world
      host: localhost
      uri: /world
      port: 9002