server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/firmys.jks
    key-password: changeit
    key-alias: firmys
    enabled: true
gameservices:
  service:
    character:
      host: localhost
      port: 8081
    inventory:
      host: localhost
      port: 8082
    users:
      host: localhost
      port: 8083
    world:
      host: localhost
      port: 8084

spring:
  application:
    name: GameServicesGateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: inventoryService
          uri: https://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path="/inventory/**"
        - id: characterService
          uri: https://${gameservices.service.character.host}:${gameservices.service.character.port}
          predicates:
            - Path=/character/**
        - id: inventoriesService
          uri: https://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path="/inventories/**"
        - id: charactersService
          uri: https://${gameservices.service.character.host}:${gameservices.service.character.port}
          predicates:
            - Path=/characters/**
        - id: itemService
          uri: https://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path="/item/**"
        - id: currencyService
          uri: https://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path=/currency/**
        - id: itemsService
          uri: http://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path="/items/**"
        - id: currenciesService
          uri: https://${gameservices.service.inventory.host}:${gameservices.service.inventory.port}
          predicates:
            - Path=/currencies/**
        - id: usersService
          uri: https://${gameservices.service.users.host}:${gameservices.service.users.port}
          predicates:
            - Path="/users/**"
        - id: worldService
          uri: https://${gameservices.service.world.host}:${gameservices.service.world.port}
          predicates:
            - Path="/world/**"
  main:
    web-application-type: reactive
springdoc:
  api-docs:
    enabled: true
  enable-spring-security: false
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    use-root-path: true