server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/firmys.jks
    key-password: changeit
    key-alias: firmys
    enabled: true
gameservices:
  services:
    - name: character
      host: ${SERVICES_CHARACTER_HOST:localhost}
      port: ${SERVICES_CHARACTER_PORT:8081}
    - name: inventory
      host: ${SERVICES_INVENTORY_HOST:localhost}
      port: ${SERVICES_INVENTORY_PORT:8082}
    - name: user
      host: ${SERVICES_USER_HOST:localhost}
      port: ${SERVICES_USER_PORT:8083}
    - name: world
      host: ${SERVICES_WORLD_HOST:localhost}
      port: ${SERVICES_WORLD_PORT:8084}
    - name: transaction
      host: ${SERVICES_TRANSACTION_HOST:localhost}
      port: ${SERVICES_TRANSACTION_PORT:8085}

spring:
  application:
    name: GameServicesGateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: inventoryService
          uri: https://${gameservices.services[1].host}:${gameservices.services[1].port}
          predicates:
            - Path="/inventory/**"
        - id: characterService
          uri: https://${gameservices.services[0].host}:${gameservices.services[0].port}
          predicates:
            - Path=/character/**
        - id: itemService
          uri: https://${gameservices.services[1].host}:${gameservices.services[1].port}
          predicates:
            - Path="/item/**"
        - id: currencyService
          uri: https://${gameservices.services[4].host}:${gameservices.services[4].port}
          predicates:
            - Path=/currency/**
        - id: userService
          uri: https://${gameservices.services[2].host}:${gameservices.services[2].port}
          predicates:
            - Path="/user/**"
        - id: worldService
          uri: https://${gameservices.services[3].host}:${gameservices.services[3].port}
          predicates:
            - Path="/world/**"
        - id: transactionService
          uri: https://${gameservices.services[4].host}:${gameservices.services[4].port}
          predicates:
            - Path="/transaction/**"
  main:
    web-application-type: reactive
springdoc:
  api-docs:
    enabled: true
  enable-spring-security: false
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    use-root-path: true