version: 2.1

jobs:
  build:
    working_directory: /home/circleci/working
    docker:
      - image: cimg/openjdk:17.0
    environment:
      PRIVATE_KEY: "id_rsa_32c94f125733ade3ed51c91845886fa6" # We have to use the specific key with the correct fingerprint
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" # Ignore errors due to known hosts
    steps: # TODO - Parallelize deploy
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 32:c9:4f:12:57:33:ad:e3:ed:51:c9:18:45:88:6f:a6
      - run:
          name: Build
          command: mvn -B -DskipTests -pl -gameservices-sdk,-gameservices-webui clean install
      - run:
          name: Prepare Workspace
          command: |
            sudo mkdir -p /home/circleci/working/project
            sudo cp gameservices-characters/target/gameservices-characters.jar /home/circleci/working/project/
            sudo cp gameservices-inventory/target/gameservices-inventory.jar /home/circleci/working/project/
            sudo cp gameservices-gateway/target/gameservices-gateway.jar /home/circleci/working/project/
            sudo cp gameservice_start.sh /home/circleci/working/project/
      - run:
          name: Prepare Environment File
          command: | # It is necessary to pass environment variables to remote environments
            echo "export SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL" > sshenv
            echo "export SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME" >> sshenv
            echo "export SPRING_DATASOURCE_SECRET=$SPRING_DATASOURCE_SECRET" >> sshenv
            echo "export SERVICE_PORT=8080" >> sshenv
            echo "export VM_HOST_INVENTORY=$VM_HOST_INVENTORY" >> sshenv
            echo "export VM_HOST_CHARACTER=$VM_HOST_CHARACTER" >> sshenv
            sudo cp sshenv /home/circleci/working/project/
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /home/circleci/working/project
          # Must be relative path from root
          paths:
            - gameservices-characters.jar
            - gameservices-inventory.jar
            - gameservices-gateway.jar
  deploy:
    parallelism: 3
    docker:
      - image: cimg/openjdk:17.0
    environment:
      PRIVATE_KEY: "id_rsa_32c94f125733ade3ed51c91845886fa6" # We have to use the specific key with the correct fingerprint
      SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" # Ignore errors due to known hosts
      WORKING_DIR: /home/circleci/working/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - 32:c9:4f:12:57:33:ad:e3:ed:51:c9:18:45:88:6f:a6
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: $WORKING_DIR
      - run:
          name: Deploy Character Service
          command: |
            ls -lah
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/sshenv ec2-user@$VM_HOST_CHARACTER:~/sshenv
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservice_start.sh ec2-user@$VM_HOST_CHARACTER:~
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservices-characters.jar ec2-user@$VM_HOST_CHARACTER:~ 
            sudo ssh -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS ec2-user@$VM_HOST_CHARACTER 'bash ./gameservice_start.sh restart'
      - run:
          name: Deploy Inventory Service
          command: |
            ls -lah
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/sshenv ec2-user@$VM_HOST_INVENTORY:~/sshenv
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservice_start.sh ec2-user@$VM_HOST_INVENTORY:~
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservices-inventory.jar ec2-user@$VM_HOST_INVENTORY:~ 
            sudo ssh -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS ec2-user@$VM_HOST_INVENTORY 'bash ./gameservice_start.sh restart'
      - run:
          name: Deploy Service Gateway
          command: |
            ls -lah
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/sshenv ec2-user@$VM_HOST_GATEWAY:~/sshenv
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservice_start.sh ec2-user@$VM_HOST_GATEWAY:~
            sudo scp -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS $WORKING_DIR/gameservices-gateway.jar ec2-user@$VM_HOST_GATEWAY:~ 
            sudo ssh -i ~/.ssh/$PRIVATE_KEY $SSH_OPTIONS ec2-user@$VM_HOST_GATEWAY 'bash ./gameservice_start.sh restart'

workflows:
  gameservices:
    jobs:
      - build:
          context: Firmys
      - deploy:
          requires:
            - build
          context: Firmys