gameservice:
  services:
    - name: inventory
      host: localhost
      uri: /inventory
      port: 9000
    - name: character
      host: localhost
      uri: /character
      port: 9001
    - name: world
      host: localhost
      uri: /world
      port: 9002