gameservices:
  type: PLAYER
  current:
    id: ${gameservices.services.${gameservices.type}.id}
    name: ${gameservices.services.${gameservices.type}.name}
    host: ${gameservices.services.${gameservices.type}.host}
    port: ${gameservices.services.${gameservices.type}.port}
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/firmys.jks
    key-alias: firmys
    enabled: true
    key-store-password: ${SSL_KEY_PASSWORD:changeit}
spring:
  cloud:
    config:
      enabled: true
      password: ${CONFIG_PASSWORD:changeit}
      uri: https://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}/
      username: ${CONFIG_USERNAME:firmys}
  profiles:
    active:
      - native
      - service
      - data
  config:
    import: "configserver:"