spring:
  security:
    user:
      name: sa
      password: password
  datasource:
    url: jdbc:mysql://java-gameservices.covj7lnh9ex6.us-west-1.rds.amazonaws.com:3306/sys
    username: firmys
    password: Ch4in.Rat
  jpa:
    hibernate:
      # Set to create if need to recreate table
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false

  health:
    defaults:
      enabled: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-1
    credentials:
      accessKey: AKIA5B6LRKJW2ITMK5NN
      secretKey: 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
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    rds:
      java-gameservice:
        password: Ch4in.Rat
server:
  port: 9000