server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/firmys.jks
    key-password: ${SSL_KEY_PASSWORD:changeit}
    key-alias: firmys
    enabled: true
  port: ${gameservices.current.port}
gameservices:
  services:
    CHARACTER:
      id: character
      name: CharacterService
      host: ${SERVICES_CHARACTER_HOST:localhost}
      port: ${SERVICES_CHARACTER_PORT:8444}
    SKILL:
      id: skill
      name: SkillService
      host: ${SERVICES_CHARACTER_HOST:localhost}
      port: ${SERVICES_CHARACTER_PORT:8444}
    STAT:
      id: stat
      name: StatService
      host: ${SERVICES_CHARACTER_HOST:localhost}
      port: ${SERVICES_CHARACTER_PORT:8444}
    RACE:
      id: race
      name: RaceService
      host: ${SERVICES_CHARACTER_HOST:localhost}
      port: ${SERVICES_CHARACTER_PORT:8444}
    INVENTORY:
      id: inventory
      name: InventoryService
      host: ${SERVICES_INVENTORY_HOST:localhost}
      port: ${SERVICES_INVENTORY_PORT:8445}
    ITEM:
      id: item
      name: ItemService
      host: ${SERVICES_INVENTORY_HOST:localhost}
      port: ${SERVICES_INVENTORY_PORT:8445}
    USER:
      id: user
      name: UserService
      host: ${SERVICES_USER_HOST:localhost}
      port: ${SERVICES_USER_PORT:8446}
    WORLD:
      id: world
      name: WorldService
      host: ${SERVICES_WORLD_HOST:localhost}
      port: ${SERVICES_WORLD_PORT:8447}
    TRANSACTION:
      id: transaction
      name: TransactionService
      host: ${SERVICES_TRANSACTION_HOST:localhost}
      port: ${SERVICES_TRANSACTION_PORT:8448}
    CURRENCY:
      id: currency
      name: CurrencyService
      host: ${SERVICES_TRANSACTION_HOST:localhost}
      port: ${SERVICES_TRANSACTION_PORT:8448}
    FLAVOR:
      id: flavor
      name: FlavorService
      protocol: http
      host: ${SERVICES_FLAVOR_HOST:localhost}
      port: ${SERVICES_FLAVOR_PORT:9000}
    CONFIG:
      id: config
      name: ConfigService
      username: ${CONFIG_USERNAME:firmys}
      password: ${CONFIG_PASSWORD:changeit}
      host: ${CONFIG_HOST:localhost}
      port: ${CONFIG_PORT:8888}
    GATEWAY: &gateway
      id: gateway
      name: GatewayService
      username: ${GATEWAY_USERNAME:firmys}
      password: ${GATEWAY_PASSWORD:changeit}
      host: ${GATEWAY_HOST:localhost}
      port: ${GATEWAY_PORT:8443}
  gateway: *gateway

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  application:
    name: ${gameservices.current.name}
  main:
    web-application-type: reactive
springdoc:
  api-docs:
    enabled: true
  enable-spring-security: false
  swagger-ui:
    enabled: true
    use-root-path: true
    path: swagger-ui.html