spring:
  graphql:
    websocket:
      path: /graphql
    cors:
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins: '*'
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      locations: classpath:META-INF/schema/**
      introspection:
        enabled: true
      inspection:
        enabled: true