spring:
  datasource:
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver
  data:
    mongodb:
      database: gameservices-${gameservices.current.id}sdb
      auto-index-creation: true
      host: "${MONGODB_HOST:localhost}"
      port: "${MONGODB_PORT:27017}"
      username: "${MONGODB_USERNAME:root}"
      password: "${MONGODB_PASSWORD:pw}"
      uri: mongodb://${spring.data.mongodb.username}:mongo${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}
