spring:
  security:
    user:
      name: sa
      password: password
  datasource:
    url: jdbc:h2:file:~/data/inventory
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-inventory
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 9000

#  CREATE TABLE Inventory (
#  `id` int NOT NULL AUTO_INCREMENT,
#  `uuid` VARCHAR(40) DEFAULT UUID() UNIQUE NOT NULL,
#  `ownedItems` VARCHAR, # Item id plus unique UUID
#  `ownedCurrency` VARCHAR, # Map of currencies by currency uuid
#  PRIMARY KEY (`id`)
#  );

  #CREATE TABLE Currency (
  #`id` int NOT NULL AUTO_INCREMENT,
  #`uuid` VARCHAR(40) DEFAULT UUID() UNIQUE NOT NULL,
  #`name` VARCHAR NOT NULL,
  #`description` VARCHAR,
  #`baseValue` int NOT NULL,
  #PRIMARY KEY (id)
  #);