CREATE TABLE IF NOT EXISTS Inventory
(
    UUID         UUID NOT NULL PRIMARY KEY,
    CHARACTER_ID UUID,
    CURRENCIES   TEXT ARRAY,
    ITEMS        TEXT ARRAY
);

CREATE TABLE IF NOT EXISTS InventoryItem
(
    UUID         UUID NOT NULL PRIMARY KEY,
    ITEM_ID      UUID,
    INVENTORY_ID UUID,
    QUANTITY     BIGINT,
    FOREIGN KEY (INVENTORY_ID) REFERENCES Inventory (uuid)
);

CREATE TABLE IF NOT EXISTS InventoryCurrency
(
    UUID         UUID NOT NULL PRIMARY KEY,
    CURRENCY_ID  UUID,
    INVENTORY_ID UUID,
    QUANTITY     BIGINT,
    FOREIGN KEY (INVENTORY_ID) REFERENCES Inventory (uuid)
);