spring:
#  main:
#    web-application-type: reactive
  security:
    user:
      name: sa
      password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: inventoryService
          uri: http://localhost:9000
          predicates:
            - Path="/inventory/**"
        - id: characterService
          uri: http://localhost:9001
          predicates:
            - Path=/character/**
management:
  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false

  health:
    defaults:
      enabled: true