CREATE TABLE IF NOT EXISTS Transaction
(
    UUID         UUID NOT NULL PRIMARY KEY,
    TYPE         VARCHAR(255),
    FUNGIBLE_ID  UUID,
    CHARACTER_ID UUID,
    DELTA        BIGINT,
    INITIAL      BIGINT,
    RESULT       BIGINT,
    TIMESTAMP    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Currency
(
    UUID        UUID NOT NULL PRIMARY KEY,
    NAME        VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);