gameservices:
  current:
    id: config
    name: ConfigService
    username: ${CONFIG_USERNAME:firmys}
    password: ${CONFIG_PASSWORD:changeit}
    host: ${CONFIG_HOST:localhost}
    port: ${CONFIG_PORT:8888}
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/firmys.jks
    key-alias: firmys
    enabled: true
    key-store-password: ${SSL_KEY_PASSWORD:changeit}
  port: ${gameservices.current.port}
spring:
  security:
    user:
      name: ${gameservices.current.username}
      password: ${gameservices.current.password}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: [ classpath:/config, file:./config ]
  application:
    name: ${gameservices.current.name}
  main:
    web-application-type: reactive